_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "3":
                - 13
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": darwin-arm64
batch_size:
    value: 2
embed_dim:
    value: 512
epochs:
    value: 10000
gpu_profiling_enabled:
    value: true
grad_accum_steps:
    value: 8
learning_rate:
    value: 0.0003
max_lr:
    value: 0.0003
max_seq_length:
    value: 512
max_steps:
    value: 10000
min_lr:
    value: 3e-06
num_blocks:
    value: 8
num_experts:
    value: 32
num_heads:
    value: 8
top_k_experts:
    value: 8
total_parameters:
    value: 3794757352
trainable_parameters:
    value: 3794757352
vocab_size:
    value: 25000
warmup_steps:
    value: 750
