_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "3":
                - 13
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 2
            "12": 0.20.1
            "13": darwin-arm64
batch_size:
    value: 4
embed_dim:
    value: 1024
epochs:
    value: 10000
grad_accum_steps:
    value: 4
learning_rate:
    value: 0.0003
max_lr:
    value: 0.0003
max_seq_length:
    value: 1024
max_steps:
    value: 10000
min_lr:
    value: 3e-06
num_blocks:
    value: 16
num_experts:
    value: 64
num_heads:
    value: 16
top_k_experts:
    value: 8
vocab_size:
    value: 50309
warmup_steps:
    value: 750
